# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/php:7.1-node-browsers
      - image: circleci/php:7
        environment:
          APP_ENV: testing
          APP_KEY: base64:D+c9WV2OBzUJMn5tftYqa+LwK1Pw9/h78jAq4ygBzPg=
          DB_DATABASE: circle_test
          DB_USERNAME: root
          SKIP_LONG_TESTS: true

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test

    # parallelism: 2
    working_directory: ~/laravel

    steps:
      - checkout

      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - run: composer --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: cp .env.circleci .env

      - run: php artisan migrate:refresh --seed --force --env=testing -vvv

      # run tests!
      - run: phpunit